---
title: Alex de Groot
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Your Username
description: Programmer From Somewhere On Earth
footer-links:
  dribbble: 
  email: agarwal.akshay.akshay8@gmail.com
  facebook: 
  flickr: 
  github: AkshayAgarwal007
  instagram: 
  linkedin: akshay-agarwal-782018a4
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
