---
title: Alex de Groot
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: 'Alex de Groot '
description: Programmer From Harderwijk On Earth
footer-links:
  dribbble: 
  email: Alex@alexdegroot.net
  facebook: 
  flickr: 
  github: Alexlepje
  instagram: Alexlepje
  linkedin: Alex. Degroot88
  pinterest: 
  rss: 
  twitter: Alexdegroot11
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
